repos:
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-case-conflict
    - id: check-ast
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
      exclude: .gitlab-ci.yml
    - id: debug-statements
-   repo: https://github.com/john-hen/Flake8-pyproject
    rev: 1.2.3
    hooks:
    -   id: Flake8-pyproject
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
    -   id: bandit
        args: [--config, pyproject.toml]
        additional_dependencies: [".[toml]"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'
    hooks:
    -   id: mypy
        additional_dependencies: [types-retry==0.9.9.4, types-requests==2.31.0.20240403]
