services:
  proxy:
    container_name: proxy
    build:
      context: src
    env_file: .env
    ports:
      - 3000:3000
  redis:
    image: redis:7.4.0-alpine3.20
    container_name: redis
    environment:
      - REDIS_PASSWORD=testpassword
      - REDIS_USER=testuser
      - REDIS_USER_PASSWORD=testuserpassword
    ports:
      - 6379:6379
